### ISSUE TITLE
use speedyseq instead of phyloseq

### ISSUE THREAD

**Issue by adw96** [adw96/DivNet#100]
[speedyseq](https://github.com/mikemc/speedyseq) is so damn fast compared to `phyloseq`, and for anywhere that we use  `tax_glom` will have significant advantages, including in the beta diversity vignette. It would also be pretty cool to promote `speedyseq`, because not everyone knows about it, and I wish more people did! 

Could we make it a `Suggests` and replace `library(phyloseq)` with `library(speedyseq)` in `beta_diversity.Rmd` and anywhere else that uses `phyloseq::tax_glom()`?  If you load speedyseq first it also loads phyloseq, but you access speedyseq's versions of all functions by default.

**Comment by svteichman** [comment]
Addressed in [this](https://github.com/adw96/DivNet/pull/103) pull request.
