### ISSUE TITLE
testBetaDiversity pseudo F-statistic calculation

### ISSUE THREAD

**Issue by pooranis** [adw96/DivNet#118]
Hello, I noticed in the calculation of the pseudo F-statistic for the Bray-Curtis distance when you calculate the bootstrapped statistics, you calculate the distance with a loop :
https://github.com/adw96/DivNet/blob/0a17eb6c06973dcd73fbca3cc376a5345c44373d/R/s3functions.R#L192-L198

Is this because of the centroid transformation?  Would the stats be very different if you used the regular Bray-Curtis formula on the ``centered_comps``?  I only ask because using a distance function like ``vegan::vegdist(X, method = 'bray')`` or ``dist(X, method = 'manhattan')`` (the latter of which can be made the same as your formula by multiplying by 0.5) is significantly faster, and for large dataset with 1000 bootstrap replicates, the loop is very costly.  So, I am curious if it would be ok to modify.  Thanks!

**Comment by adw96** [comment]
Thanks for spotting this, @pooranis. We're under a big crunch with the deadline next week, so we'll try to get back to you in early May. I've put it on my calendar to follow up, but feel free to ping us in a couple of weeks. 

Tagging @ailurophilia -- let's discuss in a couple of weeks!

**Comment by adw96** [comment]
Hi @pooranis -- It looks like you changed the issue/question significantly since I last saw it. As a result, I'm going to close this issue and ask you to open a new issue with your updated question. Thanks!
