### ISSUE TITLE
code coverage audit

### ISSUE THREAD

**Issue by adw96** [adw96/DivNet#123]
Why is code coverage so low at 53%? Can we get it up to 90% without adding significant time to testing?

**Comment by adw96** [comment]
@svteichman I just spoke with @ailurophilia who tells me that coverage was higher at some point -- perhaps a merge/PR lost some tests, or reintroduced a large untested function (phylodivnet). So this may not be as hard as it sounds, but may require some sleuthing! (Maybe this helps)

**Comment by svteichman** [comment]
Closing this issue because the code coverage is now up to 92%.
