### ISSUE TITLE
SVD failed; sigma is error

### ISSUE THREAD

**Issue by nmshahir** [adw96/DivNet#16]
hello it's me again breaking things.

I was doing a test run on my data with the base taxon set to the taxa with the highest abundance and this is the error I received

>SVD failed; sigma is 
followed by a long string of numbers of this form 
```
            [,1]        [,2]        [,3]         [,4]         [,5]         [,6]        [,7]         [,8]        [,9]      [,10]       [,11]
  [1,] 17.27093822 -0.68898413 -0.19269662 -4.162210948 -3.091394414  1.462428498  3.92078759 -1.856796600  1.20663115  6.2004287  2.45530317
```

and then
> Error in default_network(sigma) : 

Help? I'm guessing the decomposition broke down somewhere

**Comment by adw96** [comment]
Unfortunately, since I can't reproduce this error with information provided, I'm not sure how to help. Could you please provide a minimal working example so I can diagnose the error?

**Comment by adw96** [comment]
It's been a month since we heard on this; closing this issue until we get a MWE
