### ISSUE TITLE
doSNOW not a requirement

### ISSUE THREAD

**Issue by mworkentine** [adw96/DivNet#17]
Hi,

Just started playing with DivNet - looks great by the way!  One small issue - the function `MCmat` has a requirement for `doSNOW` to be installed but `doSNOW` is only in suggests and so the code will not run in parallel unless it's installed.  Not a big issue but it wasn't immediately apparent why the parallel code didn't run (and it makes a difference!)

Thanks for the great package!

**Comment by adw96** [comment]
Thanks for letting us know, @mworkentine! Sorry that this wasn't immediately apparent. We have now added a warning if `ncores` is greater than 1 but one of the packages needed for parallelisation isn't loaded. 

Thanks for helping us improve the accessibility of the software!

(ref commit fa66712)
