### ISSUE TITLE
'glue::collapse' is deprecated. Use 'glue_collapse' instead.

### ISSUE THREAD

**Issue by jvhagey** [adw96/DivNet#18]
When running the following;
 simplifyBeta(dv_ps_locB, ps, "bray-curtis", "Sample_Type")

I get the following warning:
Error: Unknown columns `282`, `283`, `284`, `285`, `286` and ...
In addition: Warning message:
'glue::collapse' is deprecated.
Use 'glue_collapse' instead.
See help("Deprecated") and help("glue-deprecated").

While trying to sort out the "Error: Unknown columns `282`, `283`, `284`, `285`, `286` and ..." part of the error, which I think is a separate issue, I discovered that the glue package has a deprecated function. Version 1.2.0 of glue uses "collapse" and glue 1.3.0 uses "glue_collapse". 

Don't know that its an urgent issue at the moment as the code still ran, but just FYI.

**Comment by adw96** [comment]
Thanks so much for letting us know, Jill! @bryandmartin  is travelling at the moment but I'll ask him to look into this when he is back next week.

@bryandmartin  It looks like it should be an easy fix (renaming collapse to glue_collapse) but we will want to do some unit tests to make sure. If we don't have a unit test that captures this could you write one? Thanks!

**Comment by bryandmartin** [comment]
I think this is a phyloseq issue, and I tested it again and it is working for me. Are you still getting this issue @jvhagey ?

**Comment by jvhagey** [comment]
@adw96 @bryandmartin Sorry,  for the late reply. The error message comes when using R 3.5.0, DivNet_0.3.0 and breakaway_4.6.7. After updating R to 3.5.2, DivNet_0.3.1 and breakaway_4.6.8 the error message isn't there so looks like its all good now.

**Comment by adw96** [comment]
Thanks for getting back to us, Jill! Glad to see we've hopefully resolved the issue but let us know if you find it again! I will close this issue for now.
