### ISSUE TITLE
Numbered samples cause error

### ISSUE THREAD

**Issue by jvhagey** [adw96/DivNet#19]
Hi Amy,

When running this command:
simplifyBeta(dv_ps_st, ps, "bray-curtis", "Sample_Type")

I get this error:
Error: Unknown columns `282`, `283`, `284`, `285`, `286` and ...

I think its coming from lines 27 & 31 in the beta_diversity_helper.R file. If you have numbered samples it puts an X in front of the number sample when it makes a dataframe and then it can't match names anymore. 

> dv_ps_locB[[measure]] %>%
     data.frame

         X282      X283      X284      X285      X286      X287      X288
282 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000

If you change lines 27 & 31 from just data.frame to data.frame(check.names =FALSE) it won't put the X in front of the number and the script runs on my end. Happy to send my phyloseq object over to make sure it works on your end. 

packageVersion("DivNet")
[1] ‘0.3.0’

**Comment by jvhagey** [comment]
Yes, `sample_names(ps)` are numbers. I agree with leaving the code as is, but just thought it would be good to open an issue so that others can be aware and have a solution. It will take a few days to rerun Divnet with the names changed and I'll let you now the out come to confirm the issue and solution. Thanks for following up!

**Comment by adw96** [comment]
👍

**Comment by jvhagey** [comment]
@adw96 After renaming samples with this: 
`sample_names(phyloseq_object) <- paste0("sample_", sample_names(phyloseq_object))`
 The error is gone and the script runs normally, yay problem solved!

**Comment by ianartmor** [comment]
Hi Amy,

Thanks for your work in this area and for making the tools user friendly!

Sorry to revive an old thread, but I had the same problem and it took me awhile to figure it out.

Would it be possible to throw an error if the physeq has sample names that begin with a number (my sample names were an alphanumeric mix but started with a number)? And in that error message suggest @jvhagey 's quick fix? That would have helped me diagnose this problem faster and might nudge novice users like myself toward better practices.

Best,
Ian
