### ISSUE TITLE
Verifying divnet 

### ISSUE THREAD

**Issue by nmshahir** [adw96/DivNet#21]
Question regarding output, if I'm getting a p-value of 0, I'm assuming that's implying that the p-value is just extremely small and the software just concatenated it to 0?

Example
`

> Hypothesis testing:
>   p-value for global test: 0 
>                          Estimates           Standard Errors     p-values
> (Intercept)             1.8138791     0.04773023             0
> predictorsnonIBD 0.6719023      0.11433915             0

**Comment by adw96** [comment]
Yes, that's right!
