### ISSUE TITLE
Error in default_network(sigma) : 

### ISSUE THREAD

**Issue by paulinetrinh** [adw96/DivNet#22]
I'm getting this "Error in default_network(sigma)" that I was trying to figure out but figured it'd probably be a lot faster to ask one of you @adw96 or @bryandmartin. 

I'm using fit_aitchison on mydata.txt which is a 73x1271 data frame (73 samples, 1271 ASV's) of relative abundances.

[my_x.txt](https://github.com/adw96/DivNet/files/2964161/my_x.txt)
[mydata.txt](https://github.com/adw96/DivNet/files/2964162/mydata.txt)

this code should produce the error
`my_w <- read.table("mydata.txt", sep="\t")`
`my_x <- read.table("my_x.txt", sep="\t")`
`divnet_estimates <- DivNet::fit_aitchison(my_w, base = 1040, X = my_x)`

what am I doing wrong? :(

**Comment by paulinetrinh** [comment]
Oh does it have something to do with the fact that my OTU_Table set as proportions? When I convert my other phyloseq objects' otu_tables to relative abundances it throws an error with creating the sigma matrix too.

**Comment by adw96** [comment]
Hi @paulinetrinh -- DivNet does expect count data as input (we could consider generalising if there is a genuine use case) *implicitly* -- I don't think we have a check for this. 

If you only get this error when you have relative abundance data and do not have this error when you have count data, I would attribute the error to not having count data. 

Can you confirm whether or not having count data fixes the issue?

**Comment by paulinetrinh** [comment]
Yes! this fixed it. Thanks Amy!

**Comment by mldillon-LBL** [comment]
Hi @adw96, 

I'm getting this error ( Error in default_network(sigma) ) but I am using count data. 

I've been trying to get divnet running on a subset of my total data, so the df is 2 samples x 36,825 otus. I'm wondering if the dimensions are a problem here?

HC_divnet <- divnet(W = HC_otu.mat)

My data are too large to upload, currently trying to run 

HC_divnet <- divnet(W = HC_otu.mat[1:2, 1:20000])

I haven't been able to find anything on the default_network() function.  Is it in divnet? Or breakaway?

Thanks!

Megan
