### ISSUE TITLE
Covariate Modeling

### ISSUE THREAD

**Issue by nmshahir** [adw96/DivNet#23]
Quick question,

is it possible include multiple covariates in DivNet?
Ex. I have five location but i have a sample from pond and a swamp from each location and want to compare the diversity between ponds and swamps controlling for the location.

Thank you!

**Comment by bryandmartin** [comment]
Hi @nmshahir,

This is certainly possible. There are examples of doing something very similar to what you are interested in the "Getting Started" vignette. To view them, after installing DivNet, type `browseVignettes(package = "DivNet")`, then click to view the PDF version of "Getting Started".

Let me know if this solves your issue.

Bryan

**Comment by nmshahir** [comment]
Sorry for the late reply! The vignette was very helpful and I think I have it working!
Best,
Nur
