### ISSUE TITLE
Boxplot alpha diversity?

### ISSUE THREAD

**Issue by PVa-Pe** [adw96/DivNet#24]
Hi, 

Sorry for my silly question, but how would you boxplot the output of alpha diversity (ie. Shannon) from DivNet? 

Thanks!

**Comment by bryandmartin** [comment]
Hi @PVa-Pe ,

As in the "Getting Started" vignette, you can extract estimates via:
`estimates <- divnet_object$shannon %>% summary %$% estimate`. 

If you want to boxplot, you can just use something like `boxplot(estimates)` or a ggplot implementation, but it would be the same as creating a boxplot from any other numeric vector in R.

Let me know if this solves your issue.

-Bryan

**Comment by PVa-Pe** [comment]
Cheers Bryan,

Issue solved!
