### ISSUE TITLE
Shannon returned all the same value

### ISSUE THREAD

**Issue by SilasK** [adw96/DivNet#25]
Hallo, I'm trying out the DivNet to calculate shannon diversity. 
I put directly the raw counts (without using phyloseq).
I got the exact same estimation of diversity for all the samples (including error) which I find suspicious. Any Idea.

**Comment by adw96** [comment]
Remember that DivNet is a regression model. If you don't add any covariates, you are essentially fitting a mean-only model, so all estimates will be the same. You can regress on covariates regarding your samples (e.g. sample type) to give you the population estimate for each sample type, or you can estimate diversity for each sample individually (e.g. using sample ID as a covariate). If you have biological replicates, consider a regression on source ID. 

Hope that helps!
