### ISSUE TITLE
DivNet runtime

### ISSUE THREAD

**Issue by mooreryan** [adw96/DivNet#28]
Do you have any info on the runtime/memory usage of the `divnet` function?  In the vignettes it says it takes a while with lots of taxa, but I was wondering if you had any more specific info.

For example, I was trying to run it on data ~300 samples by ~10,000 taxa/ASVs with covariates, but it kept crashing.  Is there a limit on taxa or samples that we should keep in mind?

**Comment by paulinetrinh** [comment]
@mooreryan wanted to confirm that using the implementation of DivNet-rs resolves this issue with wide datasets.

**Comment by mooreryan** [comment]
It works for a subset of the problems DivNet R package solves. But it's *a* working solution, so that's something!

**Comment by paulinetrinh** [comment]
Thanks Ryan! For all users, please refer to the README link to DivNet-rs on how you might use your wide dataset with DivNet. We will be adding more to our README on what DivNet methods/options are available to users via DivNet-rs. Stay tuned!
