### ISSUE TITLE
feature request: allow random effects in testDiversity

### ISSUE THREAD

**Issue by yanxianl** [adw96/DivNet#30]
Hi,

I just read the recent works from your group on estimating microbial diversity and relative abundance with measurement errors and decided to use the methods proposed. I was not aware of the pitfalls on using the observed diversity metrics as if they were the real ones until I read the papers. Great works that you have done! 

I want to compare the alpha diversity among groups with random effects. While I can use the `breakaway::betta_random` to compare the species richness , similar functions for comparing the Shannon and Simpson index are missing in the _Divnet_ package. It'd be great to also allow modelling random effects in the `testDiversity` as well.

Meanwhile, can I use `betta_random` to do hypothesis testing for Shannon and Simpon index?

Yanxian

**Comment by adw96** [comment]
Dear Yanxian --

I apologise that I did not see your question earlier. Indeed I recommend `breakaway::betta_random` for random effects in the absence of this functionality in `DivNet` at this time. 

Cheers,

Amy

**Comment by adw96** [comment]
Hi Yanxian -- I just made a new vignette in [breakaway](https://github.com/adw96/breakaway) that talks through fixed and random effects models for diversity. It includes both species richness (estimated using breakaway) and Shannon and Simpson diversity (estimated using DivNet). 

Check out the vignette here:

https://github.com/adw96/breakaway

😸

**Comment by yanxianl** [comment]
Thanks! I'll read the new tutorial.
