### ISSUE TITLE
Thank you so much, Amy, this has been really helpful!

### ISSUE THREAD

**Issue by liisaveerus** [adw96/DivNet#34]
Thank you so much, Amy, this has been really helpful! 

For other users, my data set is 350 samples * 7100 ASVs. Still struggling to get divnet() to work due to memory overload, but attempting to run this on a server.

The betta_random() works like a charm, according to your shared vignette. Just one question about the output.

results <- betta_random(chats = estimated_richness$estimate,
                                       ses = estimated_richness$error,
                                       X = model.matrix(~Organ*Health.Status, data = estimated_richness),
                                       groups=estimated_richness$Individual.ID) 

For clarification:
Organ: heart, liver, lung, kidney
Health.Status: healthy, symptomatic

<img width="411" alt="Example" src="https://user-images.githubusercontent.com/52078155/63431117-11e42600-c416-11e9-88f3-c91f06413e5d.PNG">

Are the first estimates for healthy organs and then the Health.Status:Symptomatic is for heart*symptomatic?

Thanks again!

_Originally posted by @liisaveerus in https://github.com/adw96/DivNet/issues/31#issuecomment-523431985_

**Comment by adw96** [comment]
Happy to help! Here's the interpretation of the parameter estimates:

- The "intercept" is the estimated richness in healthy Heart samples (102 taxa)
- The estimated richness in healthy Liver samples is 102+84 taxa (84 more taxa estimated to be in Liver samples than in Heart samples)
- The estimated richness in symptomatic Kidney samples is 102+84-77 (77 fewer taxa are estimated to be in symptomatic Kidney samples than healthy Kidney samples)

**Comment by mooreryan** [comment]
I had a question about interpreting the output as well....say for this example I wanted to know if there was a significant difference between Lung and Liver, or Kidney and Lung.  Is there an easy way to do some post-hoc testing with the betta output?

**Comment by adw96** [comment]
Sample code regarding switching the baseline now available at #37
