### ISSUE TITLE
DivNet/betta post-hoc testing

### ISSUE THREAD

**Issue by mooreryan** [adw96/DivNet#37]
I had a question about interpreting the output as well....say for this example I wanted to know if there was a significant difference between Lung and Liver, or Kidney and Lung.  Is there an easy way to do some post-hoc testing with the betta output?

_Originally posted by @mooreryan in https://github.com/adw96/DivNet/issues/34#issuecomment-546636633_

**Comment by mooreryan** [comment]
Figured I would open a new issue about this since it's a bit different from the original post...

**Comment by slhogle** [comment]
agree that this would be very useful

**Comment by adw96** [comment]
@slhogle and @mooreryan -- thanks for your patience. Here's how you can reorder to make `lung` the baseline for testing:

```
# some fake estimates
set.seed(1)
estimates <- runif(n = 12, min = 1000, max = 1200)
ses <- runif(n = 12, min = 1, max = 5)

# the covariates
types <- rep(c("heart", "lung", "kidney", "liver"), each = 3)
x_default <- model.matrix(~types) # heart is baseline; since alphabetically first
betta(estimates, ses, X = x_default)$table # tests w heart as default

# make lung the baseline
library(tidyverse) # not necessary, but I like `%>%`
types2 <- types %>% as.factor %>% relevel(ref = "lung")
x_lung <- model.matrix(~types2) # now with lung as baseline
betta(estimates, ses, X = x_lung)$table # now tests w lung as default
```

 I'm in the process of revising the DivNet manuscript so more improvements to DivNet are coming (including *finally* reviewing @mooreryan 's amazing work on the Rcpp implementation). Thanks again all for your patience.

Happy to answer more questions if you have any 😸 

Amy

**Comment by adw96** [comment]
By the way -- statisticians often use "post-hoc testing" to mean testing post-variable selection, rather than a predetermined all-by-all set of comparisons. The former is significantly harder to do -- so I'm relieved you were asking about the latter!

**Comment by paulinetrinh** [comment]
@ailurophilia Would you mind commenting on how this issue was addressed? :)

**Comment by ailurophilia** [comment]
Oh, unless I'm misunderstanding, the issue was resolved with the code example @adw96 posted.

**Comment by mwaak** [comment]
As someone who's been following this thread and tried using DivNet, it's not immediately clear how to use the results to perform all-by-all comparisons (e.g., multiple comparisons, pairwise comparisons or---generally---post hoc tests) to determine which group means differ among all possible comparisons. In other words, the above code example compares all organs to a single reference, but what do we do if there is no reference---we're interested in comparing all groups pairwise. Is it possible to use the results à la the _emmeans_ package, for example? Or is the recommendation here to run the example _betta_() code multiple times, each with a different organ as the reference until all organs have been treated as the baseline?
This link provides some examples of what I, for one, am used to (as a non-statistician). 
https://biostats.w.uib.no/topics/basic-stats-in-r/post-hoc-tests/

**Comment by ailurophilia** [comment]
I've created a new function in breakaway, betta_lincom(), to make estimation and inference for linear combinations of fixed effects easier. @adw96 – I'm not a contributor to the main breakaway repository, so I've opened a pull request from a forked repository to the testing branch, either for you to approve for testing or, if you'll make me a contributor on breakaway, for me to. Thanks!

**Comment by ailurophilia** [comment]
(Or for me to adjust if I've messed anything up.)

**Comment by paulinetrinh** [comment]
@mwaak Thanks so much for your question and interest! We're working on creating some additional capabilities to address this question about post-hoc testing and will clarify how to use it in an updated vignette! Stay tuned and we'll check back once we get everything up. :)

**Comment by ailurophilia** [comment]
Breakaway now includes a function, `betta_lincom`, to make interval estimation and hypothesis testing for linear combination of parameters easier.  Here's an example expanding on @adw96's above with `betta_lincom`:

`set.seed(1)
estimates <- runif(n = 12, min = 1000, max = 1200)
ses <- runif(n = 12, min = 1, max = 5)

# the covariates
types <- rep(c("heart", "lung", "kidney", "liver"), each = 3)
x_default <- model.matrix(~types) # heart is baseline; since alphabetically first
fitted_betta <- betta(estimates, ses, X = x_default) # tests w heart as default

# construct estimates, 95% CIs, hypothesis test for beta_lung - beta_liver
betta_lincom(fitted_betta,
             c(0,0,-1,1))

# construct estimates, 95% CIs, hypothesis test for beta_lung - beta_kidney

betta_lincom(fitted_betta,
             c(0,-1,0,1))`
