### ISSUE TITLE
Tutorial not working!

### ISSUE THREAD

**Issue by sushmitasp** [adw96/DivNet#38]
Link to the tutorial is broken, thanks!

**Comment by sushmitasp** [comment]
Never mind! I am guessing it's under "stamps2018/estimation/diversity-lab.R?"

**Comment by adw96** [comment]
@bryandmartin Can you please advise Sushmita on how to build & open the vignette? Thanks!

**Comment by bryandmartin** [comment]
Hi @sushmitasp ,

Please try the following (note that you may need to follow some prompts, depending on what you already have installed). Let me know if you have any troubles!

```
devtools::install_github("adw96/DivNet")
library(DivNet)
browseVignettes(package = "DivNet")
```

Bryan

**Comment by sushmitasp** [comment]
I get this:

Vignettes found by browseVignettes(package = "DivNet")
Vignettes in package DivNet
Analysing phyloseq objects - PDF  source 
Getting Started - PDF  source 

However, when I click on the source/PDF of both this is what I get:
/library/DivNet/doc/getting-started.pdf not found

Thanks for your help!

**Comment by bryandmartin** [comment]
That's odd. I'm not sure why that would be. What happens if you do the following:

`help(package = "DivNet", help_type = "html")`

then click `User guides, package vignettes and other documentation.` right under `DESCRIPTION file`, then click `PDF` of one of the vignettes.

**Comment by sushmitasp** [comment]
Okay, thanks that worked! :)
