### ISSUE TITLE
Tracking accept values in the EM loop

### ISSUE THREAD

**Issue by mooreryan** [adw96/DivNet#46]
While working on #45 I found that the acceptance values were being stored in `accept_list` but that they weren't actually being used anywhere (as far as I can tell).

It's created here:

https://github.com/adw96/DivNet/blob/ad616a02f93800eb1e63e1088fdbc74f01bf78b0/R/fit_aitchison.R#L119

And updated here during the EM iterations:

https://github.com/adw96/DivNet/blob/ad616a02f93800eb1e63e1088fdbc74f01bf78b0/R/fit_aitchison.R#L160

I can't seem to find that being used anywhere....is it necessary to track them like this?

**Comment by mooreryan** [comment]
I removed all references to those lines and the tests still passed.  So just wondering if it is something that should be used anywhere or if it is okay to remove.

**Comment by mooreryan** [comment]
Ah, I just saw this....I actually removed tracking them in #47, but if you want I can try and put them back in!

**Comment by svteichman** [comment]
Closing this issue because I just checked fit_aitchison.R, and both lines 119 and 160 are there tracking the accept values. Thanks for your help Ryan!
