### ISSUE TITLE
DivNet error bars

### ISSUE THREAD

**Issue by mooreryan** [adw96/DivNet#59]
I had a question regarding how to describe error bars in DivNet figures.

Here are the relevant lines of code: 

Variance is the `var` function:

```R
  output_list[["shannon-variance"]]  <- list_of_fitted_models %>% 
    lapply(function(x) sapply(x$shannon, function(x) x$estimate)) %>%
    simplify2array %>%
    apply(1, var, na.rm = TRUE)
```

`error` is square root of variance, (so standard deviation)

https://github.com/adw96/DivNet/blob/160daaf21d3ba49d46c2f987c798ce32e6cb8fe8/R/divnet_main.R#L156

and the `interval` is twice the SD in both directions:

https://github.com/adw96/DivNet/blob/160daaf21d3ba49d46c2f987c798ce32e6cb8fe8/R/divnet_main.R#L157

So if I were to describe the error bars in a manuscript, what would be the best way?  Something like: "error bars represent four standard deviations" or "error bars represent two standard deviations from the mean" or something else?

**Comment by adw96** [comment]
Hi @mooreryan ! What a summer, yeesh. Sorry for not getting back to you sooner. I would use one of the following: 
- "Error bars represent a 95% confidence interval for the true mean Shannon diversity [in group X]"
- "Error bars represent +/- 2 two standard errors in estimating the mean Shannon diversity [in group X]"
Hope that helps!
