### ISSUE TITLE
Release of the package

### ISSUE THREAD

**Issue by llrs** [adw96/DivNet#60]
Hi! Many thanks for providing these methods in such an easy way as this package does!.

Is there any plan to release them in any repository like Bioconductor or CRAN?
I've seen that breakaway [was on CRAN](https://cran.r-project.org/package=breakaway) for some years but was later removed. This would make possible for other packages on CRAN and Bioconductor to use these methods. 
This would also imply that all the dependencies would need to be on CRAN. Not sure if [there is](https://github.com/adw96/breakaway/issues/41) room for such move.

**Comment by adw96** [comment]
Thanks for this question! At present, there are no plans to release the package in Bioconductor or CRAN. Unfortunately there is a huge overhead in doing this, and we are instead prioritising package maintenance and new package development. Thanks for your understanding. Maybe one day!
