### ISSUE TITLE
INPUT of divnet() 

### ISSUE THREAD

**Issue by ari9609** [adw96/DivNet#66]
Hi
I have a doubt about the input of divnet() function
Can I use absolute or relative abundance table with the function divnet indistinctly , or is it necessary to use relative abundance table?
Thanks :smiley:

**Comment by mooreryan** [comment]
You can use a count table as input.  In fact, the test data set (`Lee`) used in the [DivNet vignette](https://github.com/adw96/DivNet/blob/master/vignettes/getting-started.Rmd) is a count table.
