### ISSUE TITLE
Include DIVNET-rs alternate implementation on DIVNET homepage

### ISSUE THREAD

**Issue by benyoung93** [adw96/DivNet#71]
Good Afternoon 

It was just an idea I had but it may be really useful to include @mooreryan alternate implementation of DIVNET (DIVNET-rs) in the read me for the package (i.e. the DIVNET homepage page on github). 

I would never of found it if I had not been scowering through the issues to see if anyone had had any luck with running on a large number of ASVs (for reference I have 9000 ASVs with 290 samples). 

If this is not possible or you do not want to do this then I completely understand just thought I would open an issue to see if it was possible :). I also apologise I have no idea how to add a enhancement/suggestion label. 

Have a wonderful day. 

PS. Also, DIVNET and Breakaway are fantastic, my first time doing 16s analysis and this is a much more rigorous statistical way to test alpha hypothesis !

**Comment by paulinetrinh** [comment]
For those interested, we have updated the README to include a reference to DIVNET-rs!
