### ISSUE TITLE
simplifyBeta does not work with special characters in sample names

### ISSUE THREAD

**Issue by aimirza** [adw96/DivNet#73]
After removing special characters from my sample names, `simplifyBeta()` finally stops producing the error:

```
Error: Can't subset columns that don't exist.
x Columns `A-1-PT-06_S11`, `A-2-PT-04_S16`, `A-3-PT-05_S4`, `A-4-PT-02_S15`, `A-5-PT-02_S14`, etc. don't exist.
```
I removed all of the underscores and dashes and it finally worked. Would be nice if `simplifyBeta()` can work with special characters

**Comment by svteichman** [comment]
Hi @aimirza, I'm working on this issue but having trouble reproducing your error. Could you please provide a minimal working example of sample names that are throwing this error? Thank you for identifying this!

**Comment by svteichman** [comment]
Actually, if this is the same error that Mike is showing in this pull request https://github.com/adw96/DivNet/pull/62 I can work with his example.

**Comment by paulinetrinh** [comment]
Non-standard characters in sample names will be flagged in order to prevent potential future conflicts with R operations/functions.
