### ISSUE TITLE
Beta diversity test for binomial covariate

### ISSUE THREAD

**Issue by aimirza** [adw96/DivNet#75]
I couldn't find any example showing how to perform a test comparing differences in a beta diversity measure between two groups of samples. May you please provide an example?

**Comment by adw96** [comment]
Thanks for your patience @aimirza -- David (@ailurophilia ) is currently working on this. We'll update you soon 👍

**Comment by aimirza** [comment]
Awesome. When should we expect to see the tutorial?

**Comment by adw96** [comment]
I'm not sure, but in the meantime I'm going to close this issue and encourage you to subscribe to #67 instead. Thanks!
