### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by adw96** [adw96/DivNet#87]
@svteichman @paulinetrinh @ailurophilia -- is all of the additional functionality added over this summer covered by additional unit tests? If not, could you please create some? 

This will make sure that future alterations for the codebase do not cause errors in your new functions 🌟 

Let's not close this issue until we have code coverage >70% (or some explanation for why some functions cannot be covered by tests).

**Comment by paulinetrinh** [comment]
87%! 
For details on what was done: https://github.com/adw96/DivNet/pull/108

**Comment by adw96** [comment]
(Amy moves head in an excited circular motion)
